# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  paymentsapi:
    image: paymentsapi
    build:
      context: .
      dockerfile: Payments.Api/Dockerfile
    ports:
      - 5002:80

  orderapi:
    image: orderapi
    build:
      context: .
      dockerfile: Order.Api/Dockerfile
    ports:
      - 5001:80

  apigateway:
    image: apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - 5000:80